In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('./summary/Dataset_SummaryStatistics_University.csv')
df

,Student_ID,Department,Gender,Age,GPA,Credits_Completed,Attendance,Scholarship
0,S1152,CSE,Female,20.0,10.00,140.0,65.54,No
1,S1260,ECE,Male,18.0,10.00,140.0,73.51,Yes
2,S1253,ME,Male,23.0,10.00,140.0,66.95,No
3,S1004,EEE,Male,21.0,10.00,140.0,80.00,No
4,S1345,ECE,Male,23.0,9.96,140.0,5.00,No
...,...,...,...,...,...,...,...,...
347,S1166,CE,Male,24.0,5.00,41.0,94.63,Yes
348,S1003,EEE,Female,24.0,4.50,24.0,39.37,No
349,S1002,ME,Female,18.0,0.00,25.0,73.13,No
350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.describe()#Summary of the data

              Age         GPA  Credits_Completed  Attendance
count  350.000000  350.000000         350.000000  350.000000
mean    20.925714    7.466543         116.311429   71.541486
std      2.035550    1.070520          37.225521   17.686022
min     18.000000    0.000000          20.000000    5.000000
25%     19.000000    6.862500          98.000000   60.625000
50%     21.000000    7.470000         140.000000   71.205000
75%     23.000000    8.120000         140.000000   80.970000
max     24.000000   10.000000         140.000000  200.000000

In [10]:
print('Mean ', df['GPA'].mean())
print('Median ', df['GPA'].median())
print('Mode ', df['GPA'].mode()[0])
print('Population Standard Deviation ', df['GPA'].std(ddof = 0))
print('Sample Standard Deviation ', df['GPA'].std(ddof = 1))

Mean  7.466542857142857
Median  7.47
Mode  6.98
Population Standard Deviation  1.0689900665810603
Sample Standard Deviation  1.0705204754771773

In [12]:
print(df['Department'].value_counts())

Department
CE     81
CSE    80
ME     71
ECE    61
EEE    57
Name: count, dtype: int64

In [14]:
print(df['Gender'].value_counts())

Gender
Male      178
Female    172
Name: count, dtype: int64

In [16]:
df['Gender'].mode()

0    Male
Name: Gender, dtype: object

In [18]:
df.select_dtypes(include='number').mean()

Age                   20.925714
GPA                    7.466543
Credits_Completed    116.311429
Attendance            71.541486
dtype: float64

In [20]:
df.count()

Student_ID           350
Department           350
Gender               350
Age                  350
GPA                  350
Credits_Completed    350
Attendance           350
Scholarship          350
dtype: int64

In [22]:
df.max(numeric_only=True)

Age                   24.0
GPA                   10.0
Credits_Completed    140.0
Attendance           200.0
dtype: float64

In [24]:
df.min(numeric_only=True)

Age                  18.0
GPA                   0.0
Credits_Completed    20.0
Attendance            5.0
dtype: float64

In [26]:
df['GPA'].var()

np.float64(1.146014088415882)

In [28]:
df['Credits_Completed'].std()

np.float64(37.225520957547204)

In [29]:
df.groupby('Gender')['GPA'].mean()

Gender
Female    7.460465
Male      7.472416
Name: GPA, dtype: float64